### ISSUE TITLE
unconfigure/install prototype change

### ISSUE THREAD

**Issue by drzraf** [kwivix/flexinline#1]
On `symfony/flex` v1.2.0
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Flex\Configurator::unconfigure(), 1 passed in /usr/share/php/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 147 and exactly 2 expected in /home/vendor/symfony/flex/src/Configurator.php:57
Stack trace:
#0 /usr/share/php/Composer/Plugin/PluginManager.php(195) : eval()'d code(147): Symfony\Flex\Configurator->unconfigure(Object(Symfony\Flex\Recipe))
#1 /usr/share/php/Composer/Plugin/PluginManager.php(195) : eval()'d code(98): Kwivix\FlexInline\ComposerPlugin_composer_tmp0->processPackageEvent(Object(Composer\Installer\PackageEvent))
#2 [internal function]: Kwivix\FlexInline\ComposerPlugin_composer_tmp0->postPackageUninstall(Object(Composer\Installer\PackageEvent))
#3 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Installer\PackageEvent))
#4 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(116): Composer\EventDispatcher\EventDispatcher->doDispatch(Objec in /home/vendor/symfony/flex/src/Configurator.php on line 57
```

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Flex\Configurator::install(), 1 passed in /usr/share/php/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 149 and at least 2 expected in /home/vendor/symfony/flex/src/Configurator.php:47
Stack trace:
#0 /usr/share/php/Composer/Plugin/PluginManager.php(195) : eval()'d code(149): Symfony\Flex\Configurator->install(Object(Symfony\Flex\Recipe))
#1 /usr/share/php/Composer/Plugin/PluginManager.php(195) : eval()'d code(88): Kwivix\FlexInline\ComposerPlugin_composer_tmp0->processPackageEvent(Object(Composer\Installer\PackageEvent))
#2 [internal function]: Kwivix\FlexInline\ComposerPlugin_composer_tmp0->postPackageInstall(Object(Composer\Installer\PackageEvent))
#3 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Installer\PackageEvent))
#4 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(116): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Compose in /home/vendor/symfony/flex/src/Configurator.php on line 47
```

**Comment by drzraf** [comment]
ping?
